### ISSUE TITLE
how to specify custom .. settings

### ISSUE THREAD

**Issue by hardevine** [barchart/laravel-remember-all#1]
- custom column name for user_id 
- indefinite expiry date for tokens
- store user agent ip, data 
- able to sign out of specific device

**Comment by tomsisk** [comment]
Personally, I feel like 3 and 4 may be out of scope, and come with privacy concerns. Willing to hear arguments to the contrary, however.

1 and 2, you can open a pull request, or I can get around to this next week.

**Comment by tomsisk** [comment]
@hardevine After some thought, I'm going to keep things as-is.

I recommend a higher expiration time for "indefinite" expirations. The tokens will refresh and extend that time on each use of the token. For instance, if your session time is two hours and the token is set at the default of 7 days, it does not mean that token is only good for 7 days. After your session expires, we will use the token to keep you logged in and extend the token by 7 more days (the token also gets updated). I think this suffices and is more secure (you can determine how secure you want it to be, but I don't think "forever" is very secure at all).

As for customizing the `user_id` column, I'm not sure I see the use-case right now. Since the plan is to open this as a pull request to Laravel core (going to try to do this sometime this week, need to write tests), I would rather keep the changes as minimal as possible. That can be something discussed within that pull request or in the future.

As for 3 and 4, I still think this is out of scope. What we can, and probably should, do is fire an event when a new token is created. At that point, you could add whatever information you want to, either to your own modified `remember_tokens` table or a separate table. Does that work?
